version: '2.1'
volumes:
  db:
    driver: local

services:
  osticket:
    image: trydirect/osticket:1.12
    build: build
    container_name: osticket
    restart: always
    links:
      - db
    depends_on:
      - db
#    ports:
#      - "80:80"
#      - "443:443"

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql

  nginx:
    image: trydirect/nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - osticket
    links:
      - osticket
    ports:
      - "80:80"
    volumes:
      - ./configs/nginx/conf.d:/etc/nginx/conf.d/
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
